openapi: 3.0.0
info:
  title: Laravel API Documentation
  description: Documentação das APIs do Laravel
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
tags:
  - name: User
    description: User workflow
  - name: Signature
    description: Signature workflow
  - name: Invoice
    description: Invoice workflow
paths:
  /user/getall:
    get:
      summary: Lista todos os users
      responses:
        '200':
          description: Sucesso
      tags:
        - User
  /user/get/{id}:
    get:
      summary: Obtém um user pelo ID
      parameters:
        - name: id
          in: path
          description: ID do user a ser obtido
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Sucesso
        '404':
          description: User não encontrado
      tags:
        - User
  /user/insert:
    post:
      summary: Insere um novo user
      # requestBody:
      #   required: true
      #   content:
      #     application/json:
      #       schema:
      #         $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User criado com sucesso
      tags:
        - User
  /user/update/{id}:
    put:
      summary: Atualiza um user existente pelo ID
      parameters:
        - name: id
          in: path
          description: ID do user a ser atualizado
          required: true
          schema:
            type: integer
      # requestBody:
      #   required: true
      #   content:
      #     application/json:
      #       schema:
      #         $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User atualizado com sucesso
        '404':
          description: User não encontrado
      tags:
        - User
  /user/delete/{id}:
    delete:
      summary: Exclui um user pelo ID
      parameters:
        - name: id
          in: path
          description: ID do user a ser excluído
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: User excluído com sucesso
        '404':
          description: User não encontrado
      tags:
        - User
  /signature/getall:
    get:
      summary: Lista todas as signatures
      responses:
        '200':
          description: Sucesso
      tags:
        - Signature
  /signature/get/{id}:
    get:
      summary: Obtém uma signature pelo ID
      parameters:
        - name: id
          in: path
          description: ID da signature a ser obtida
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Sucesso
        '404':
          description: Signature não encontrada
      tags:
        - Signature
  /signature/insert:
    post:
      summary: Insere uma nova signature
      # requestBody:
      #   required: true
      #   content:
      #     application/json:
      #       schema:
      #         $ref: '#/components/schemas/Signature'
      responses:
        '201':
          description: Signature criada com sucesso
      tags:
        - Signature
  /signature/update/{id}:
    put:
      summary: Atualiza uma signature existente pelo ID
      parameters:
        - name: id
          in: path
          description: ID da signature a ser atualizada
          required: true
          schema:
            type: integer
      # requestBody:
      #   required: true
      #   content:
      #     application/json:
      #       schema:
      #         $ref: '#/components/schemas/Signature'
      responses:
        '200':
          description: Signature atualizada com sucesso
        '404':
          description: Signature não encontrada
      tags:
        - Signature
  /signature/delete/{id}:
    delete:
      summary: Exclui uma signature pelo ID
      parameters:
        - name: id
          in: path
          description: ID da signature a ser excluída
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Signature excluída com sucesso
        '404':
          description: Signature não encontrada
      tags:
        - Signature
  /invoice/getall:
    get:
      summary: Lista todas as invoices
      responses:
        '200':
          description: Sucesso
      tags:
        - Invoice
  /invoice/get/{id}:
    get:
      summary: Obtém uma invoice pelo ID
      parameters:
        - name: id
          in: path
          description: ID da invoice a ser obtida
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Sucesso
        '404':
          description: Invoice não encontrada
      tags:
        - Invoice
  /invoice/insert:
    post:
      summary: Insere uma nova invoice
      # requestBody:
      #   required: true
      #   content:
      #     application/json:
      #       schema:
      #         $ref: '#/components/schemas/Invoice'
      responses:
        '201':
          description: Invoice criada com sucesso
      tags:
        - Invoice
  /invoice/update/{id}:
    put:
      summary: Atualiza uma invoice existente pelo ID
      parameters:
        - name: id
          in: path
          description: ID da invoice a ser atualizada
          required: true
          schema:
            type: integer
      # requestBody:
        # required: true
        # content:
          # application/json:
            # schema:
              # $ref: '#/components/schemas/Invoice'
      responses:
        '200':
          description: Invoice atualizada com sucesso
        '404':
          description: Invoice não encontrada
      tags:
        - Invoice
  /invoice/delete/{id}:
    delete:
      summary: Exclui uma invoice pelo ID
      parameters:
        - name: id
          in: path
          description: ID da invoice a ser excluída
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Invoice excluída com sucesso
        '404':
          description: Invoice não encontrada
      tags:
        - Invoice
