name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Laravel Rsync Deploy
      uses: SHSharkar/Laravel-Rsync-Deploy@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "--ignore-times --compress --verbose --exclude=.git --exclude=.github --exclude=node_modules --no-perms --no-owner --no-group --recursive"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_HOST_PORT: ${{ secrets.REMOTE_HOST_PORT }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET_DIRECTORY: ${{ secrets.TARGET_DIRECTORY }}
